# Generated by Django 5.1.7 on 2025-04-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="previews/"),
        ),
    ]
